export const MAZE_SIZE = {
  MIN: 5,
  MAX: 80,
  DEFAULT_GENERATE: 21,
  DEFAULT_CUSTOM_EDITOR: 12,
} as const;

export const MESH_REDUCTION = {
  MIN_THRESHOLD: 5,
  MAX_THRESHOLD: 200,
  DEFAULT_THRESHOLD: 25,
  DEFAULT_ENABLED: true,
} as const;

export const CAMERA_ZOOM_LIMIT = {
  MIN_DISTANCE_MIN: 0.5,
  MAX_DISTANCE_MAX: 5000,
  DEFAULT_MIN_DISTANCE: 2,
  DEFAULT_MAX_DISTANCE: 100,
  DEFAULT_ENABLED: true,
} as const;

export const ADAPTIVE_QUALITY = {
  DEFAULT_SCALE: 1.0,
  STABLE_PIXEL_RATIO_CAP: 1.25,
  INTERACTION_PIXEL_RATIO_CAP: 0.85,
  MIN_PIXEL_RATIO: 0.5,
  MIN_SCALE: 0.6,
  MAX_SCALE: 1.0,
  DECREASE_STEP: 0.08,
  INCREASE_STEP: 0.04,
  HIGH_FRAME_TIME_MS: 26,
  LOW_FRAME_TIME_MS: 16,
  UPDATE_COOLDOWN_MS: 280,
  EMA_ALPHA: 0.18,
} as const;

export const ADAPTIVE_QUALITY_DEFAULT_SCALE = ADAPTIVE_QUALITY.DEFAULT_SCALE;

export const SOLUTION_PATH = {
  COLOR: 0xff3b30,
  LINE_WIDTH: 3,
  OPACITY: 0.95,
  Y_OFFSET: 0.04,
} as const;

export const SOLUTION_PATH_LINE_WIDTH = {
  MIN: 1,
  MAX: 12,
  DEFAULT: 6,
} as const;

export const FLOOR_GRID_Y_OFFSET = 0.001;

export const MAZE_RENDER_TIMING = {
  INTERACTION_END_DELAY_MS: 120,
  INITIAL_QUALITY_UPGRADE_DELAY_MS: 300,
} as const;

export const MULTI_LAYER_MAZE = {
  OPENING_CELL_VALUE: 2,
  OPENING_NORTH_CELL_VALUE: 3,
  OPENING_EAST_CELL_VALUE: 4,
  OPENING_SOUTH_CELL_VALUE: 5,
  OPENING_WEST_CELL_VALUE: 6,
  STAIR_STEP_COUNT: 4,
} as const;
